### ISSUE TITLE
Errors when creating hurtle

### ISSUE THREAD

**Issue by ayatullah-ayat** [Muhammad-Sarfaraz/Hurtle#8]
![image](https://github.com/user-attachments/assets/f7ff7cd2-77e6-483b-bdc5-8b668f31cbbe)

Unable to create the repo in local

**Comment by Muhammad-Sarfaraz** [comment]
@ayatullah-ayat The issue has been resolved, Thanks. See commit [dd876e0](https://github.com/username/repo/commit/abc1234](https://github.com/Muhammad-Sarfaraz/Hurtle/commit/dd876e027d42f606fc92aebf398f5656ff6a6d18)) for further  details.
